name: .NET Aspire CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Aspire Workload
      run: dotnet workload install aspire

    # Run dotnet commands inside the `api` folder where the solution lives.
    - name: Restore dependencies
      working-directory: api
      run: dotnet restore FriendNetApp.sln

    - name: Build
      working-directory: api
      run: dotnet build FriendNetApp.sln --no-restore --configuration Release

    - name: Run Auth Tests
      env:
        JWTSECRET: ${{ secrets.JWTSECRET }}
        DOTNET_ENVIRONMENT: Development
        working-directory: api
        run: dotnet test FriendNetApp.IntegrationTests/FriendNetApp.IntegrationTests.csproj --filter "FullyQualifiedName~RegisterCreateGetAll" --no-build --verbosity normal

    - name: Run Messaging Tests
      env:
        JWTSECRET: ${{ secrets.JWTSECRET }}
        DOTNET_ENVIRONMENT: Development
        working-directory: api
        run: dotnet test FriendNetApp.IntegrationTests/FriendNetApp.IntegrationTests.csproj --filter "FullyQualifiedName~MessagingFunctionalTests" --no-build --verbosity normal

    - name: Run Social Tests
      env:
        JWTSECRET: ${{ secrets.JWTSECRET }}
        DOTNET_ENVIRONMENT: Development
        working-directory: api
        run: dotnet test FriendNetApp.IntegrationTests/FriendNetApp.IntegrationTests.csproj --filter "FullyQualifiedName~SocialFunctionalTests" --no-build --verbosity normal

    - name: Run Extended Integration Tests
      env:
        JWTSECRET: ${{ secrets.JWTSECRET }}
        DOTNET_ENVIRONMENT: Development
        working-directory: api
        run: dotnet test FriendNetApp.IntegrationTests/FriendNetApp.IntegrationTests.csproj --filter "FullyQualifiedName~ExtendedScenariosTests" --no-build --verbosity normal